### ISSUE TITLE
Broken manual matches links

### ISSUE THREAD

**Issue by azakolyukina** [iangow/se_links#11]
@iangow 

While reconciling big5 data, I have noticed that some of the old manual matches links are broken or not valid anymore. For instance, a person does not exist in that conference call anymore. My guess it is caused by the update of calls, e.g., for some calls, transcript of a call has changed. 

It would be great to figure out a process for cleaning up these manual links.

**Comment by iangow** [comment]
@azakolyukina You need to be more precise here. Which tables, etc.? If possible, which matches disappeared? I've not done anything related  to links of individuals on Equilar to names on StreetEvents in a very long time. But in principle, there should be a company-level match and then a person-level match. Links could break down at either step.

**Comment by azakolyukina** [comment]
@iangow 

> You need to be more precise here. Which tables, etc.? If possible, which matches disappeared? 

I think all manual match tables related to firm or executive links will be affected. 

The easy way to check that is to use the manual matches links and try to link them to the updated `speaker_data`. Some of these manual matches will not be there. 

> But in principle, there should be a company-level match and then a person-level match. Links could break down at either step.

Yes, the question is should we do anything about broken manual match links or not. I think we should. The easy way is to remove the links that do not exist in `speaker_data` anymore.This can happen because: (1) call was deleted when you removed duplicates; (2) `file_name` was erroneously assigned to a different transcript content and that was later corrected (This is how the extraversion result from the first version of big5 has disappeared)

**Comment by azakolyukina** [comment]
@iangow 

@jingyujzhang was adding manual matches incrementally, i.e., these manual matches gsheets will contain new matches. The straightforward way to clean them up is to drop links that are not compatible with `speaker_data` anymore.

Do you have other thoughts? If not, I can just assign this task to @jingyujzhang

**Comment by iangow** [comment]
> @iangow
> 
> @jingyujzhang was adding manual matches incrementally, i.e., these manual matches gsheets will contain new matches. The straightforward way to clean them up is to drop links that are not compatible with `speaker_data` anymore.
> 
> Do you have other thoughts? If not, I can just assign this task to @jingyujzhang

I'm not really sure which GoogleSheets are used in the manual matches of *executives* or where these manual match tables are. Perhaps best to assign to  @jingyujzhang. But if you want to dig deeper, perhaps @jingyujzhang could flag some examples of matches that have disappeared (say, `speaker_name` and `file_name`) and I could do a little digging. (If some of the manual matches are from 2013 or earlier, then they may not have been valid matches in the first place.)

**Comment by azakolyukina** [comment]
@jingyujzhang 

Could you please do the following: 
* see discussion above
* post here links to all the googlesheets with manual matches you use for `se_links` data
* flag matches that have disappeared from current `se_data` and move these matches to the separate sheet in the **same googlesheet**, say broken_links(?). If is probably not worth to investigate why they are gone, but it would be good to know which ones a gone and spot check for possible reasons

**Comment by jingyujzhang** [comment]
Manual matches (from [se_links](https://github.com/iangow/se_links) and [equilar_links](https://github.com/iangow/equilar_links)):
[first_name_pairs](https://docs.google.com/spreadsheets/d/1Yafgmt7hYjgzy30k5v41Cx7-uiiTvmvvgl8MHjDf4yc/edit#gid=662537496)
[manual_permno_matches](https://docs.google.com/spreadsheets/d/14F6zjJQZRsf5PonOfZ0GJrYubvx5e_eHMV_hCGe42Qg/edit#gid=1613221647)
[cik_mismatches](https://docs.google.com/spreadsheets/d/1XA_V-_g5eR52YaQLfA29Vkjch3yE8IOyu6xpxPCaX8s/edit#gid=494504254)
[gvkey_mismatches](https://docs.google.com/spreadsheets/d/1_yI9xJhfy3Y2npaKq6E_OoTs56hoWBb9k3axDMvzqVQ/edit#gid=1409702631)
[cusip_mismatches](https://docs.google.com/spreadsheets/d/1ExSkaxeIBs4rqH9U3_1x3klZIeHR6Fy6wS3ReR7I0dE/edit#gid=668076466)

Used in `se_exec_link`:
[executive_manual_matches](https://docs.google.com/spreadsheets/d/1n2OgXzqFlvegHdlnvoitXGuwxbBai77_FqIyhPbua3c/)
[dup_names](https://docs.google.com/spreadsheets/d/1_pfRfmnlDupuegUeOTAxI9hzXKlS017jrzSu4b6T4rA)
[speaker_filename](https://docs.google.com/spreadsheets/d/1SVDYjvxR8KV7tOfr0IpCXNqmI8Sia_7cSChLuv-SFvY/)

**Comment by azakolyukina** [comment]
@jingyujzhang 

Thanks for listing all manual match tables used in `se_links`. Note that some of them are NOT affected by changes in StreetEvents data discussed above

> [first_name_pairs](https://docs.google.com/spreadsheets/d/1Yafgmt7hYjgzy30k5v41Cx7-uiiTvmvvgl8MHjDf4yc/edit#gid=662537496)
> [cik_mismatches](https://docs.google.com/spreadsheets/d/1XA_V-_g5eR52YaQLfA29Vkjch3yE8IOyu6xpxPCaX8s/edit#gid=494504254)
> [gvkey_mismatches](https://docs.google.com/spreadsheets/d/1_yI9xJhfy3Y2npaKq6E_OoTs56hoWBb9k3axDMvzqVQ/edit#gid=1409702631)
> [cusip_mismatches](https://docs.google.com/spreadsheets/d/1ExSkaxeIBs4rqH9U3_1x3klZIeHR6Fy6wS3ReR7I0dE/edit#gid=668076466)

This will NOT be affected by the issues with `se` data

> [manual_permno_matches](https://docs.google.com/spreadsheets/d/14F6zjJQZRsf5PonOfZ0GJrYubvx5e_eHMV_hCGe42Qg/edit#gid=1613221647)

How would you identify that these links are not valid anymore?

Are you sure you have posted all googlesheet links that you use to create `se_call_link` and `se_exec_link`?

**Comment by jingyujzhang** [comment]
>How would you identify that these links are not valid anymore?

I compared company name from `calls` and `speaker_data`.
>Are you sure you have posted all googlesheet links that you use to create` se_call_link` and `se_exec_link`?

Please find all googlesheets involved [here](https://github.com/iangow/se_links/issues/11#issuecomment-583569936).

I added a new sheet `broken_links` in [executive_manual_matches](https://docs.google.com/spreadsheets/d/1n2OgXzqFlvegHdlnvoitXGuwxbBai77_FqIyhPbua3c/). For now, both the company level and executive level matches are clean.

``` r
library(RPostgreSQL)
#> Loading required package: DBI
library(dplyr, warn.conflicts = FALSE)

pg <- dbConnect(PostgreSQL())

calls <- tbl(pg, sql("select * from streetevents.calls"))
speaker_data <- tbl(pg, sql("select * from streetevents.speaker_data"))
speaker_data_old <- tbl(pg, sql("select * from streetevents_old.speaker_data"))
se_call_link <- tbl(pg, sql("select * from executive.se_call_link"))
se_exec_link <- tbl(pg, sql("select * from executive.se_exec_link"))
se_exec_link_old <- tbl(pg, sql("select * from executive.se_exec_link_old"))

# Company level
se_call_link %>% 
    anti_join(calls, by = "file_name")
#> # Source:   lazy query [?? x 4]
#> # Database: postgres 10.0.12 [jingyuzhang@128.135.196.23:54320/postgres]

se_call_link %>% 
    anti_join(speaker_data, by = c("file_name")) %>% 
    count() 
# This is because new speaker_data table has fewer rows. 
# All file_names can be found in calls
#> # Source:   lazy query [?? x 1]
#> # Database: postgres 10.0.12 [jingyuzhang@128.135.196.23:54320/postgres]
#>       n
#>   <dbl>
#> 1    94

speaker_data %>% count()
#> # Source:   lazy query [?? x 1]
#> # Database: postgres 10.0.12 [jingyuzhang@128.135.196.23:54320/postgres]
#>          n
#>      <dbl>
#> 1 29051425
speaker_data_old %>% count()
#> # Source:   lazy query [?? x 1]
#> # Database: postgres 10.0.12 [jingyuzhang@128.135.196.23:54320/postgres]
#>          n
#>      <dbl>
#> 1 30742773

# Executive level
se_exec_link %>% 
    anti_join(speaker_data, by = c("file_name")) %>% 
    anti_join(se_call_link, by = c("file_name")) %>% 
    print(n=Inf) 
#> # Source:   lazy query [?? x 5]
#> # Database: postgres 10.0.12 [jingyuzhang@128.135.196.23:54320/postgres]

se_exec_link %>% 
    anti_join(speaker_data, by = c("file_name"))
#> # Source:   lazy query [?? x 5]
#> # Database: postgres 10.0.12 [jingyuzhang@128.135.196.23:54320/postgres]

se_exec_link %>% 
    anti_join(speaker_data, by = c("file_name", "speaker_name"))
#> # Source:   lazy query [?? x 5]
#> # Database: postgres 10.0.12 [jingyuzhang@128.135.196.23:54320/postgres]

se_exec_link %>% count()
# Source:   lazy query [?? x 1]
# Database: postgres 10.0.12 [jingyuzhang@128.135.196.23:54320/postgres]
       n
   <dbl>
1 364699
se_exec_link_old %>% count()
# Source:   lazy query [?? x 1]
# Database: postgres 10.0.12 [jingyuzhang@128.135.196.23:54320/postgres]
       n
   <dbl>
1 364663

```

Created on 2020-02-23 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by azakolyukina** [comment]
@jingyujzhang 

Looks good. Thank you for doing that.
