### ISSUE TITLE
Look at code in old repository

### ISSUE THREAD

**Issue by iangow** [iangow/se_links#13]
Do we need any code from [here](https://github.com/iangow/streetevents_private/tree/master/db_matches)?

**Comment by iangow** [comment]
There are three repositories now: `se_core` (core code for parsing StreetEvents), `se_links` (this one) for link tables, and `se_features`, which pulls together "linguistic features" as applied to StreetEvents data. I plan to pull out the core functions in `se_features` and make them a Pip-installable "linguistic features" Python package that could be used for anything (not just StreetEvents). So then `se_features` would just be code for applying those to StreetEvents data.

I would not put anything related to FactSet in any of these repositories. And I doubt that much useful to FactSet could be found in these. Parsing issues will be different. Linking issues will probably be different. And `se_features` would be easier to work with once the core functions are moved to a separate package.

**Comment by azakolyukina** [comment]
Got it. Thanks.

Will see how much similarity is there soon.
